apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: url-shortener-api
  labels:
    app: url-shortener-api
spec:
  selector:
    matchLabels:
      app: url-shortener-api
  replicas: 3
  template:
    metadata:
      labels:
        app: url-shortener-api
    spec:
      containers:
      - name: url-shortener-api
        image: gcr.io/dark-garden-166716/url-shortener-api:1.0.0
        # imagePullPolicy: Never
        ports:
        - containerPort: 3001
