version: "3"
services:
  authen-api:
    image: gcr.io/${project_id}/authen-api:${version}
    build: ../../authen-api
    # deploy:
    #   replicas: 3
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 10M
    #   restart_policy:
    #     condition: on-failure
    ports:
      - "3000:3000"
    # networks:
    #   - webnet
  url-shortener-api:
    image: gcr.io/${project_id}/url-shortener-api:${version}
    build: ../../url-shortener-api
    ports:
      - "3001:3001"
  url-shortener-app:
    image: gcr.io/${project_id}/url-shortener-app:${version}
    build:
      context: ../../url-shortener-app
      dockerfile: Dockerfile.dev
        # args:
        #   buildno: 1
    ports:
      - "8080:8080"
# networks:
#   webnet: