apiVersion: v1
kind: Service
metadata:
  name: url-shortener-app-service
  labels:
    run: url-shortener-app-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    # targetPort: 3000
    protocol: TCP
    # name: http
  selector:
    run: url-shortener-app-deployment
