apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: url-shortener-app
  labels:
    app: url-shortener-app
spec:
  selector:
    matchLabels:
      app: url-shortener-app
  replicas: 3
  template:
    metadata:
      labels:
        app: url-shortener-app
    spec:
      containers:
      - name: url-shortener-app
        image: gcr.io/dark-garden-166716/url-shortener-app:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
