apiVersion: v1
kind: Service
metadata:
  name: authen-api
  labels:
    run: authen-api
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    run: authen-api